import { BottomTabInset, MaxContentWidth } from '@/constants/theme';
import { exercises, type Exercise } from '@/data/exercises';
import { createWorkoutExercise, normalizeProgram, programsStorageKey, setNumbers, type Program, type SetEntry } from '@/data/programs';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { useEffect, useMemo, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

const emptyProgram: Program = { id: '', name: '', days: [{ name: 'Day 1', exercises: [] }] };

export default function ExploreScreen() {
	const [programs, setPrograms] = useState<Program[]>([]);
	const [program, setProgram] = useState<Program>(emptyProgram);
	const [selectedDay, setSelectedDay] = useState(0);
	const [query, setQuery] = useState('');
	const [loaded, setLoaded] = useState(false);

	useEffect(() => { AsyncStorage.getItem(programsStorageKey).then(value => { if (value) setPrograms(JSON.parse(value).flatMap((item: unknown) => { const normalized = normalizeProgram(item); return normalized ? [normalized] : []; })); }).catch(() => undefined).finally(() => setLoaded(true)); }, []);
	useEffect(() => { if (loaded) AsyncStorage.setItem(programsStorageKey, JSON.stringify(programs)).catch(() => undefined); }, [programs, loaded]);

	const filteredExercises = useMemo(() => exercises.filter(exercise => exercise.name.toLowerCase().includes(query.toLowerCase())), [query]);
	const currentDay = program.days[selectedDay] ?? program.days[0];
	const updateCurrentDay = (update: (day: Program['days'][number]) => Program['days'][number]) => setProgram(current => ({ ...current, days: current.days.map((day, index) => index === selectedDay ? update(day) : day) }));
	const addExercise = (exercise: Exercise) => updateCurrentDay(day => day.exercises.some(item => item.name === exercise.name) ? day : { ...day, exercises: [...day.exercises, createWorkoutExercise(exercise.name)] });
	const removeExercise = (name: string) => updateCurrentDay(day => ({ ...day, exercises: day.exercises.filter(exercise => exercise.name !== name) }));
	const updateExerciseSet = (exerciseName: string, setIndex: number, field: keyof SetEntry, value: string) => updateCurrentDay(day => ({ ...day, exercises: day.exercises.map(exercise => exercise.name !== exerciseName ? exercise : { ...exercise, sets: exercise.sets.map((set, index) => index === setIndex ? { ...set, [field]: value } : set) }) }));
	const addDay = () => { setProgram(current => ({ ...current, days: [...current.days, { name: `Day ${current.days.length + 1}`, exercises: [] }] })); setSelectedDay(program.days.length); };
	const saveProgram = () => { if (!program.name.trim()) { Alert.alert('Name your program', 'Add a name before saving.'); return; } const saved = { ...program, id: program.id || `program-${Date.now()}`, name: program.name.trim() }; setPrograms(current => [...current.filter(item => item.id !== saved.id), saved]); setProgram(saved); Alert.alert('Saved locally', 'Your program is stored on this phone.'); };
	const loadProgram = (saved: Program) => { setProgram(saved); setSelectedDay(0); };
	const newProgram = () => { setProgram({ ...emptyProgram, days: [{ name: 'Day 1', exercises: [] }] }); setSelectedDay(0); };

	return <View style={styles.container}><SafeAreaView style={styles.safeArea}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
		<Text style={styles.eyebrow}>SLATER GYM / PROGRAM BUILDER</Text><Text style={styles.title}>Build your week.</Text><Text style={styles.subtitle}>Create a routine from the canonical exercise library and keep it on your phone.</Text>
		<View style={styles.topActions}><Pressable onPress={newProgram} style={styles.secondaryButton}><Text style={styles.secondaryText}>NEW PROGRAM</Text></Pressable><Pressable onPress={saveProgram} style={styles.primaryButton}><Text style={styles.primaryText}>SAVE PROGRAM</Text></Pressable></View>
		<Text style={styles.label}>Program name</Text><TextInput value={program.name} onChangeText={name => setProgram(current => ({ ...current, name }))} placeholder="My weekly plan" placeholderTextColor="#9A948B" style={styles.input} />
		<Text style={styles.sectionTitle}>Training days</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.dayRow}>{program.days.map((day, index) => <Pressable key={`${day.name}-${index}`} onPress={() => setSelectedDay(index)} style={[styles.dayButton, selectedDay === index && styles.dayButtonActive]}><Text style={[styles.dayText, selectedDay === index && styles.dayTextActive]}>{day.name}</Text></Pressable>)}<Pressable onPress={addDay} style={styles.addDay}><Text style={styles.addDayText}>+ DAY</Text></Pressable></ScrollView>
		{currentDay && <View style={styles.dayCard}><TextInput value={currentDay.name} onChangeText={name => updateCurrentDay(() => ({ ...currentDay, name }))} style={styles.dayNameInput} /><Text style={styles.muted}>{currentDay.exercises.length} exercises · 5 sets each</Text>{currentDay.exercises.map(exercise => <View key={exercise.name} style={styles.selectedExercise}><View style={setStyles.exerciseHeader}><Text style={styles.selectedText}>{exercise.name}</Text><Pressable onPress={() => removeExercise(exercise.name)}><Text style={styles.removeText}>REMOVE</Text></Pressable></View><View style={setStyles.setHeader}><Text style={setStyles.setHeaderText}>SET</Text><Text style={setStyles.setHeaderText}>WEIGHT</Text><Text style={setStyles.setHeaderText}>REPS</Text></View>{exercise.sets.map((set, index) => <View key={`${exercise.name}-${index}`} style={setStyles.setRow}><Text style={setStyles.setNumber}>{setNumbers[index]}</Text><TextInput value={set.weight} onChangeText={value => updateExerciseSet(exercise.name, index, 'weight', value)} placeholder="kg" placeholderTextColor="#9A948B" keyboardType="decimal-pad" style={setStyles.setInput} /><TextInput value={set.reps} onChangeText={value => updateExerciseSet(exercise.name, index, 'reps', value)} placeholder="reps" placeholderTextColor="#9A948B" keyboardType="number-pad" style={setStyles.setInput} /></View>)}</View>)}</View>}
		<Text style={styles.sectionTitle}>Add from exercise library</Text><TextInput value={query} onChangeText={setQuery} placeholder="Search exercises" placeholderTextColor="#9A948B" style={styles.input} />{filteredExercises.map(exercise => <Pressable key={exercise.id} onPress={() => addExercise(exercise)} style={styles.exerciseRow}><View><Text style={styles.exerciseName}>{exercise.name}</Text><Text style={styles.muted}>{exercise.primaryMuscle} · {exercise.equipment} · {exercise.type}</Text></View><Text style={styles.addText}>{currentDay?.exercises.some(item => item.name === exercise.name) ? 'ADDED' : '+ ADD'}</Text></Pressable>)}
		{programs.length > 0 && <><Text style={styles.sectionTitle}>Saved programs</Text>{programs.map(saved => <Pressable key={saved.id} onPress={() => loadProgram(saved)} style={styles.savedRow}><View><Text style={styles.exerciseName}>{saved.name}</Text><Text style={styles.muted}>{saved.days.length} days · {saved.days.reduce((count, day) => count + day.exercises.length, 0)} exercises</Text></View><Text style={styles.addText}>OPEN</Text></Pressable>)}</>}
	</ScrollView></SafeAreaView></View>;
}

const styles = StyleSheet.create({ container: { backgroundColor: '#F5F1EA', flex: 1 }, safeArea: { alignSelf: 'center', maxWidth: MaxContentWidth, paddingBottom: BottomTabInset, width: '100%' }, content: { padding: 20, paddingBottom: 90 }, eyebrow: { color: '#71826F', fontSize: 10, fontWeight: '900', letterSpacing: 1.5, marginBottom: 8 }, title: { color: '#1C2A22', fontSize: 30, fontWeight: '900' }, subtitle: { color: '#847D72', fontSize: 14, lineHeight: 21, marginBottom: 22, marginTop: 5 }, topActions: { flexDirection: 'row', gap: 8, marginBottom: 22 }, primaryButton: { backgroundColor: '#C76D3B', borderRadius: 8, flex: 1, paddingVertical: 13 }, primaryText: { color: '#FFF', fontSize: 11, fontWeight: '900', textAlign: 'center' }, secondaryButton: { backgroundColor: '#E7E1D7', borderRadius: 8, flex: 1, paddingVertical: 13 }, secondaryText: { color: '#1C2A22', fontSize: 11, fontWeight: '900', textAlign: 'center' }, label: { color: '#716C63', fontSize: 11, fontWeight: '800', marginBottom: 6 }, input: { backgroundColor: '#FFFDFA', borderColor: '#E2DBD0', borderRadius: 8, borderWidth: 1, color: '#1C2A22', marginBottom: 18, padding: 12 }, sectionTitle: { color: '#1C2A22', fontSize: 19, fontWeight: '900', marginBottom: 12, marginTop: 10 }, dayRow: { gap: 8, paddingBottom: 14 }, dayButton: { backgroundColor: '#FFFDFA', borderColor: '#E2DBD0', borderRadius: 8, borderWidth: 1, paddingHorizontal: 16, paddingVertical: 11 }, dayButtonActive: { backgroundColor: '#1D2D24' }, dayText: { color: '#716C63', fontWeight: '900' }, dayTextActive: { color: '#FFF' }, addDay: { borderColor: '#719174', borderRadius: 8, borderWidth: 1, paddingHorizontal: 14, paddingVertical: 11 }, addDayText: { color: '#48654C', fontSize: 11, fontWeight: '900' }, dayCard: { backgroundColor: '#FFFDFA', borderColor: '#E2DBD0', borderRadius: 10, borderWidth: 1, marginBottom: 18, padding: 14 }, dayNameInput: { color: '#1C2A22', fontSize: 17, fontWeight: '900', marginBottom: 3 }, selectedExercise: { borderTopColor: '#E2DBD0', borderTopWidth: 1, paddingVertical: 12 }, selectedText: { color: '#1C2A22', flex: 1, fontWeight: '800' }, removeText: { color: '#C76D3B', fontSize: 10, fontWeight: '900' }, exerciseRow: { alignItems: 'center', backgroundColor: '#FFFDFA', borderBottomColor: '#E2DBD0', borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', padding: 13 }, exerciseName: { color: '#1C2A22', fontSize: 14, fontWeight: '900' }, muted: { color: '#847D72', fontSize: 11, marginTop: 4 }, addText: { color: '#48654C', fontSize: 10, fontWeight: '900' }, savedRow: { alignItems: 'center', backgroundColor: '#E4EDE2', borderRadius: 8, flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8, padding: 13 } });

const setStyles = StyleSheet.create({ exerciseHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 }, setHeader: { flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 4 }, setHeaderText: { color: '#847D72', flex: 1, fontSize: 9, fontWeight: '900', textAlign: 'center' }, setRow: { alignItems: 'center', flexDirection: 'row', gap: 6, marginTop: 6 }, setNumber: { color: '#C76D3B', fontSize: 11, fontWeight: '900', textAlign: 'center', width: 28 }, setInput: { backgroundColor: '#F5F1EA', borderColor: '#E2DBD0', borderRadius: 6, borderWidth: 1, color: '#1C2A22', flex: 1, paddingHorizontal: 8, paddingVertical: 8, textAlign: 'center' } });

