import { BottomTabInset, MaxContentWidth } from '@/constants/theme';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

const historyStorageKey = '@gym/training-history';
function dateKey(date: Date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`; }
function normalizeHistory(value: unknown): Record<string, number> { if (Array.isArray(value)) return Object.fromEntries(value.filter((item): item is string => typeof item === 'string').map(item => [item, 0])); if (!value || typeof value !== 'object') return {}; return Object.fromEntries(Object.entries(value).filter(([key, seconds]) => /^\d{4}-\d{2}-\d{2}$/.test(key) && typeof seconds === 'number').map(([key, seconds]) => [key, Math.max(0, Math.floor(seconds as number))])); }
function duration(seconds: number) { return seconds < 60 ? `${seconds}s` : `${Math.floor(seconds / 60)}m`; }

export default function ProgressScreen() {
  const [history, setHistory] = useState<Record<string, number>>({});
  useFocusEffect(useCallback(() => { AsyncStorage.getItem(historyStorageKey).then(value => setHistory(value ? normalizeHistory(JSON.parse(value)) : {})).catch(() => setHistory({})); }, []));
  const today = new Date();
  const mondayOffset = (today.getDay() + 6) % 7;
  const monday = new Date(today.getFullYear(), today.getMonth(), today.getDate() - mondayOffset);
  const week = Array.from({ length: 7 }, (_, index) => new Date(monday.getFullYear(), monday.getMonth(), monday.getDate() + index));
  const trainedDays = Object.keys(history).filter(key => history[key] > 0).length;
  const weekSeconds = week.reduce((total, day) => total + (history[dateKey(day)] ?? 0), 0);
  const recent = Object.entries(history).sort(([left], [right]) => right.localeCompare(left)).slice(0, 12);

  return <View style={styles.container}><SafeAreaView style={styles.safeArea}><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>FORGED FITNESS / PROGRESS</Text><Text style={styles.title}>Your training history.</Text><Text style={styles.subtitle}>See your consistency, session time, and the days you showed up.</Text><View style={styles.stats}><Stat value={String(trainedDays)} label="days trained" /><Stat value={duration(weekSeconds)} label="this week" /><Stat value={String(Object.keys(history).length)} label="total sessions" /></View><Text style={styles.sectionTitle}>This week</Text><View style={styles.calendar}>{week.map(day => { const seconds = history[dateKey(day)] ?? 0; const trained = Object.prototype.hasOwnProperty.call(history, dateKey(day)); return <View key={dateKey(day)} style={styles.calendarDay}><Text style={styles.weekday}>{day.toLocaleDateString(undefined, { weekday: 'short' }).slice(0, 2).toUpperCase()}</Text><View style={[styles.dayCircle, trained && styles.dayCircleActive]}><Text style={[styles.check, trained && styles.checkActive]}>{trained ? '✓' : ''}</Text></View><Text style={styles.date}>{day.getDate()}</Text><Text style={styles.dayDuration}>{trained ? duration(seconds) : '-'}</Text></View>; })}</View><Text style={styles.sectionTitle}>Recent sessions</Text>{recent.length ? recent.map(([key, seconds]) => <View key={key} style={styles.sessionRow}><View><Text style={styles.sessionDate}>{new Date(`${key}T12:00:00`).toLocaleDateString(undefined, { weekday: 'long', month: 'short', day: 'numeric' })}</Text><Text style={styles.sessionSubtext}>Workout completed</Text></View><Text style={styles.sessionDuration}>{duration(seconds)}</Text></View>) : <View style={styles.empty}><Text style={styles.emptyTitle}>No sessions yet</Text><Text style={styles.emptyText}>Start a session from one of your programs on Home.</Text></View>}</ScrollView></SafeAreaView></View>;
}

function Stat({ value, label }: { value: string; label: string }) { return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ container: { backgroundColor: '#F5F1EA', flex: 1 }, safeArea: { alignSelf: 'center', maxWidth: MaxContentWidth, paddingBottom: BottomTabInset, width: '100%' }, content: { padding: 20, paddingBottom: 100 }, eyebrow: { color: '#71826F', fontSize: 10, fontWeight: '900', letterSpacing: 1.5 }, title: { color: '#1C2A22', fontSize: 30, fontWeight: '900', marginTop: 18 }, subtitle: { color: '#847D72', fontSize: 14, lineHeight: 21, marginTop: 6 }, stats: { flexDirection: 'row', gap: 8, marginTop: 24 }, stat: { backgroundColor: '#E4EDE2', borderRadius: 10, flex: 1, padding: 13 }, statValue: { color: '#1C2A22', fontSize: 20, fontWeight: '900' }, statLabel: { color: '#48654C', fontSize: 10, fontWeight: '800', marginTop: 3 }, sectionTitle: { color: '#1C2A22', fontSize: 19, fontWeight: '900', marginBottom: 12, marginTop: 28 }, calendar: { backgroundColor: '#FFFDFA', borderColor: '#E2DBD0', borderRadius: 12, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', padding: 14 }, calendarDay: { alignItems: 'center', flex: 1 }, weekday: { color: '#847D72', fontSize: 9, fontWeight: '900' }, dayCircle: { alignItems: 'center', backgroundColor: '#F5F1EA', borderColor: '#E2DBD0', borderRadius: 15, borderWidth: 1, height: 30, justifyContent: 'center', marginVertical: 7, width: 30 }, dayCircleActive: { backgroundColor: '#719174', borderColor: '#719174' }, check: { color: '#B8B0A5', fontSize: 14, fontWeight: '900' }, checkActive: { color: '#FFF' }, date: { color: '#1C2A22', fontSize: 11, fontWeight: '800' }, dayDuration: { color: '#48654C', fontSize: 9, fontWeight: '900', marginTop: 3 }, sessionRow: { alignItems: 'center', backgroundColor: '#FFFDFA', borderColor: '#E2DBD0', borderRadius: 10, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8, padding: 14 }, sessionDate: { color: '#1C2A22', fontSize: 13, fontWeight: '900' }, sessionSubtext: { color: '#847D72', fontSize: 11, marginTop: 4 }, sessionDuration: { color: '#C76D3B', fontSize: 15, fontWeight: '900' }, empty: { backgroundColor: '#FFFDFA', borderColor: '#E2DBD0', borderRadius: 10, borderWidth: 1, padding: 16 }, emptyTitle: { color: '#1C2A22', fontSize: 16, fontWeight: '900' }, emptyText: { color: '#847D72', fontSize: 13, marginTop: 5 } });
